# Generated by Django 5.2 on 2025-04-28 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('complaint_type', models.CharField(choices=[('waste_dumping', 'Waste Dumping'), ('public_nuisance', 'Public Nuisance'), ('traffic_violations', 'Traffic Violations'), ('water_leakage', 'Water Leakage'), ('street_light', 'Street Light Issue'), ('noise_pollution', 'Noise Pollution'), ('illegal_construction', 'Illegal Construction'), ('stray_animals', 'Stray Animals'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('proof', models.FileField(blank=True, null=True, upload_to='image/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.signup')),
            ],
        ),
    ]
