# Generated by Django 5.2 on 2025-07-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_admincomplaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincomplaint',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='adminComplaint',
        ),
    ]
